version: '3.8'

services:
  web:
    build: .
    image: ahmed8badr/python-app:latest #image name
    ports:
      - "5002:5002"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jay
      MYSQL_DATABASE: BucketList
      MYSQL_USER: jay
      MYSQL_PASSWORD: jay
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
