apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskapp-config
data:
  MYSQL_DATABASE: BucketList
  MYSQL_DATABASE_HOST: localhost

---

apiVersion: v1
kind: Secret
metadata:
  name: flaskapp-secret
type: Opaque
stringData:
  SECRET_KEY: 'why would I tell you my secret key?'

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: jay
